dtb-$(CONFIG_MACH_XIAOMI_DAISY) += daisy-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_SAKURA) += sakura-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_VINCE) += vince-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_YSL) += ysl-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_MIDO) += mido-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_TIFFANY) += tiffany-titanium.dtb
dtb-$(CONFIG_MACH_XIAOMI_TISSOT) += tissot-titanium.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo